version: "3.4"
services:
  app:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    ports:
      - 8076:8000
    command: ./main_tap